import type { NextPage } from 'next'
import Head from 'next/head'
import Gallery from "react-photo-gallery";
import { useCallback, useState } from "react";
import Carousel, { Modal, ModalGateway } from "react-images";
import React from "react"
React.useLayoutEffect = React.useEffect

const Blog: NextPage = () => {

  const photos = [
    {
      src: '/images/img-2.jpg',
      width: 4,
      height: 3
    },
    {
      src: '/images/img-1.jpg',
      width: 1,
      height: 1
    }
  ];

  const [currentImage, setCurrentImage] = useState(0);
  const [viewerIsOpen, setViewerIsOpen] = useState(false);

  const openLightbox = useCallback((event, { photo, index }) => {
    setCurrentImage(index);
    setViewerIsOpen(true);
  }, []);

  const closeLightbox = () => {
    setCurrentImage(0);
    setViewerIsOpen(false);
  };


  return (
    <div className="home-page">
      <Head>
        <title>Blog Page</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div>Blog page</div>
      <Gallery photos={photos} onClick={openLightbox}/>;

      <ModalGateway>
        {viewerIsOpen ? (
          <Modal onClose={closeLightbox}>
            <Carousel
              currentIndex={currentImage}
              views={photos.map(x => ({
                ...x,
                source: x.src
              }))}
            />
          </Modal>
        ) : null}
      </ModalGateway>

    </div>
  )
}

export default Blog