import type { NextPage } from 'next'
import Head from 'next/head'
import FormContact from "../components/FormContact";
import React from "react";
import MapContainer from "../components/MapContainer";

const Contact: NextPage = () => {

  return (
    <div className="contact-page">
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className="contact-container">
        <div className="text-container">
          <p className="contact">Contattaci</p>
          <h1>Richiedi un preventivo</h1>
        </div>
        <FormContact/>
      </div>
      <div className="map-container">
        <div className="text-container">
          <h1>Dove ci troviamo</h1>
          <span className="street">Castello ursino, Catania</span>
        </div>
        <MapContainer/>
      </div>
      <style jsx>{`
        .contact-container {
          display: flex;
        }
        .contact-container > *:nth-child(1) {
          flex: 0 0 30%;
        }
        .wrapper > *:nth-child(2) {
          flex: 0 0 70%;
        }
        .text-container {
          display: flex;
          flex-direction: column;
          justify-content: center;
          flex: 0 0 30%;
          margin-left: 100px;
        }
        .form-container {
          position: absolute;
          top: 100px;
        }
        .map-container {
          display: flex;
          height: 350px;
          margin-top: 50px;
        }
        @media (max-width: 600px) {
          .contact-container {
            //margin-top: 10px;
            display: flex;
            flex-direction: column;
          }
          .text-container {
            margin: 20px 20px 10px 20px;
            font-size: 13px;
            font-weight: 100;
          }
          .contact {
            display: none;
          }
          .map-container {
            height: 100%;
            display: flex;
            flex-direction: column;
            margin: 20px 0 100px 0 ;
          }
        }
      `}</style>
    </div>
  )
}

export default Contact;