import type { NextPage } from 'next'
import Head from 'next/head'
import React from "react";

const Home: NextPage = () => {
  return (
    <div className="home-page">
      <Head>
        <title>Web Page</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div >
      <h1>Check out these EPIC Destinations!</h1>
      </div>
    </div>

  )
}

export default Home
