import type { NextPage } from 'next'
import Head from 'next/head'
import React from "react";
import HeroSection from "../components/HeroSection";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="home-page">
      <Head>
        <title>Web Page</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div >
        {/*<HeroSection/>*/}
      <h1>Check out these EPIC Destinations!</h1>
       <Link href='/gallery/1'>aaa</Link><br/>
       <Link href='/gallery/2'>bbb 22</Link>
      </div>
    </div>

  )
}

export default Home
